name: "Node.js Setup Workflow"

on:
  push:

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Reposetory"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Check Node.js version"
        run: node -v

      - name: "check directories"
        run: ls

      - name: "install dipendencies"
        run: npm install

      - name: "check directories"
        run : ls
        
